# 硬件配置文件
camera:
  device_id: 0
  width: 640
  height: 480
  fps: 30
  auto_exposure: true
  exposure: -5
  gain: 0
  white_balance: 4000
  virtual_mode: true  # 启用虚拟摄像头模式

# 机械臂配置
robot_arm:
  enabled: true
  type: "virtual"       # 机械臂类型: virtual, uarm
  virtual_mode: true    # 启用虚拟机械臂模式
  
  # uArm 机械臂配置
  uarm:
    port: null          # 串口端口，null表示自动检测
    baudrate: 115200
    speed_factor: 100   # 速度系数 (1-100)
    timeout: 1.0
  
  # 位置配置 (单位: 毫米和度)
  positions:
    home:        # 初始位置
      x: 115
      y: -3
      z: 45
      rotation: 0
    
    # 货物拾取位置
    pickup_position:
      x: 115
      y: -3
      z: 45
      rotation: 0
    
    # 垃圾桶投放位置（与 uArm 实现保持一致）
    drop_positions:
      banana:         # 香蕉皮 - 厨余垃圾
        x: 200
        y: 50
        z: 50
      beverages:      # 饮料瓶 - 可回收垃圾
        x: 200
        y: -50
        z: 50
      cardboard_box:  # 纸盒 - 可回收垃圾
        x: 150
        y: 50
        z: 50
      chips:          # 薯片袋 - 其他垃圾
        x: 150
        y: -50
        z: 50
      fish_bones:     # 鱼骨 - 厨余垃圾
        x: 250
        y: 50
        z: 50
      instant_noodles: # 泡面盒 - 其他垃圾
        x: 250
        y: -50
        z: 50
      milk_box_type1:  # 牛奶盒1 - 可回收垃圾
        x: 180
        y: 30
        z: 50
      milk_box_type2:  # 牛奶盒2 - 可回收垃圾
        x: 180
        y: -30
        z: 50
      plastic:        # 塑料 - 可回收垃圾
        x: 220
        y: 0
        z: 50

  # 运动参数
  motion:
    speed: 50          # 运动速度 (mm/s)
    acceleration: 100  # 加速度 (mm/s²)
    precision: 1       # 定位精度 (mm)
    max_reach: 350     # 最大工作半径 (mm)
    max_payload: 500   # 最大负载 (g)
    degrees_of_freedom: 3  # 自由度

# 传感器配置
sensors:
  virtual_mode: true    # 启用虚拟传感器模式
  weight_sensor:
    enabled: true
    port: "/dev/ttyUSB1"
    baudrate: 9600
    
  distance_sensor:
    enabled: true
    trigger_pin: 18
    echo_pin: 24
    max_distance: 400  # cm

# GPIO配置 (适用于树莓派等)
gpio:
  led_pins:
    power: 2
    status: 3
    error: 4
  button_pins:
    start: 17
    stop: 18
    reset: 27 